### ISSUE TITLE
Implement core's orchestration

### ISSUE THREAD

**Issue by kaustavdm** [muktakosh/unicorn#3]
- [x] Create a `core` module

---

- [ ] Implement `messages` support. Depends on #2.
- [ ] Implement `messages` integration with `gateway`.
- [ ] Implement `messages` integration with `datastore`
- [ ] Implement `messages` integration with `channelhandler`

---

- [ ] Implement bringing up a `channelhandler` on new connection
- [ ] Implement instructing `channelhandler` to bring up `dataelements`
- [ ] Implement storing and retrieving data to/from `datastore`.

---

- [ ] Match Matrix specs implemented in #5.

**Comment by kaustavdm** [comment]
Not necessary with the revised architecture.
