### ISSUE TITLE
Implement basic datastore

### ISSUE THREAD

**Issue by kaustavdm** [muktakosh/unicorn#4]
Implement a key-value `datastore` which stores things in-memory.

- [ ] Create a `datastore` module
- [ ] Implement messages support. Depends on #2 
- [ ] Implement `put` interface for storing data
- [ ] Implement `get` interface for retrieving data

**Comment by asdofindia** [comment]
In-memory as in not permanent? What are some things that will be stored in this datastore?

**Comment by kaustavdm** [comment]
Does not need to be permanent initially. The focus is on speed, vs., permanent storage. Things stored include session (call) data, user tokens, registry related information.

Currently trying out Redis. Almost have a working version. Will polish and upload.
