### ISSUE TITLE
Implement basic channelhandler

### ISSUE THREAD

**Issue by kaustavdm** [muktakosh/unicorn#6]
- [x] Create a module for `channelhandler`.
- [ ] Implement messages support
- [ ] Implement support for creating and controlling `dataelements`
- [ ] Implement RTC negotiation for connecting directly with clients
- [ ] Implement reporting of RTC status to `core`

---

### SFU

- [ ] Implement basic SFU for picking and forwarding text streams

**Comment by kaustavdm** [comment]
Not necessary with the revised architecture.
