### ISSUE TITLE
Implement dataelement with text capabilities

### ISSUE THREAD

**Issue by kaustavdm** [muktakosh/unicorn#7]
- [x] Create a module for `dataelements`
- [ ] Implement data structure for storing user-agent metadata
- [ ] Implement data structure for channeling text streams

**Comment by kaustavdm** [comment]
Not necessary with the revised architecture.
